CREATE TABLE [dbo].[tbl_Kiroku_KInstances](
	[ui_instanceid] [uniqueidentifier] NULL,
	[dt_instancestart] [datetime] NULL,
	[dt_instancestop] [datetime] NULL,
	[i_duration]  AS (datediff(millisecond,[dt_instancestart],[dt_instancestop])),
	[ui_applicationid] [nvarchar](20) NULL,
	[nvc_trackid] [nvarchar](20) NULL,
	[nvc_regionid] [nvarchar](20) NULL,
	[nvc_clusterid] [nvarchar](20) NULL,
	[nvc_deviceid] [nvarchar](20) NULL,
	[nvc_klogversion] [nvarchar](20) NULL
) ON [PRIMARY]