CREATE TABLE [dbo].[tbl_KirokuG2_Metric](
	[dt_session] [smalldatetime] NULL,
	[nvc_id] [nvarchar](50) NULL,
	[nvc_source] [nvarchar](50) NULL,
	[nvc_function] [nvarchar](50) NULL,
	[i_type] [int] NULL,
	[nvc_key] [nvarchar](50) NULL,
	[d_value] [decimal](10,2) NULL
) ON [PRIMARY]