CREATE NONCLUSTERED INDEX [index_Block_instanceid] ON [dbo].[tbl_Kiroku_KBlocks]
(
	[ui_blockid] ASC
)
INCLUDE ([ui_instanceid]) 
WITH (PAD_INDEX = OFF, 
STATISTICS_NORECOMPUTE = OFF, 
SORT_IN_TEMPDB = OFF, 
DROP_EXISTING = OFF, 
ONLINE = OFF, 
ALLOW_ROW_LOCKS = ON, 
ALLOW_PAGE_LOCKS = ON)
GO

CREATE NONCLUSTERED INDEX [index_Block_blockstart] ON [dbo].[tbl_Kiroku_KBlocks]
(
	[dt_blockstart] ASC
)
WITH (PAD_INDEX = OFF, 
STATISTICS_NORECOMPUTE = OFF, 
SORT_IN_TEMPDB = OFF, 
DROP_EXISTING = OFF, 
ONLINE = OFF, 
ALLOW_ROW_LOCKS = ON, 
ALLOW_PAGE_LOCKS = ON)
GO